library(data.table)
Sys.setlocale("LC_TIME", "English")
dt <- read.table("household_power_consumption.txt", na.strings = "?", header = T, sep = ";")
dt <- dt[dt$Date=="1/2/2007" | dt$Date=="2/2/2007",]
dt$datetime <- as.POSIXct(paste(dt$Date, dt$Time), format = "%d/%m/%Y %H:%M:%S")
png("plot4.png")
par(mfrow=c(2,2))
plot(dt$datetime, dt$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(dt$datetime, dt$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(dt$datetime, dt$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
lines(dt$datetime, dt$Sub_metering_2, type="l", col="red")
lines(dt$datetime, dt$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = c(1,1))
plot(dt$datetime, dt$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()